image: phpmyadmin/phpmyadmin:${{PMA_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-dbadmin-phpmyadmin
networks:
#! if has service mysql {
#!   - mysql-phpmyadmin
#! }
#! if has service mariadb {
#!   - mariadb-phpmyadmin
#! }
ports:
  - ${{PMA_PORT}}:80
volumes:
  - /sessions
env_file:
  - environment.env
depends_on:
  - database