image: phpmyadmin/phpmyadmin:${{PMA_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-dbadmin-phpmyadmin
networks:
#? if services.database contains name == "mysql" {
#   - mysql-phpmyadmin
#? }
#? if services.database contains name == "mariadb" {
#   - mariadb-phpmyadmin
#? }
ports:
  - ${{PMA_PORT}}:80
volumes:
  - ${{VOLUME_PMA_SESSIONS}}:/sessions
env_file:
  - environment.env
depends_on:
  - database