image: jupyter/${{JUPYTER_NOTEBOOK_TYPE}}:${{JUPYTER_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-frontend-jupyter
restart: always
volumes:
  - ${{VOLUME_JUPYTER_DATA}}:/home/jovyan/work
networks:
#? if has services.database {
#  - frontend-database
#? }
ports:
  - ${{JUPYTER_PORT}}:8888