version: 2
updates:
  # Golang dependency updates
  - package-ecosystem: gomod
    directory: /src
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer

  # Main Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer

  # NPM
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer