project_name: compose-generator
builds:
  - dir: src
    main: ./compose-generator.go
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 5
      - 6
      - 7
      - 8
    ldflags:
      - -s -w -X compose-generator/util.Version={{ .Version }} -X compose-generator/util.Commit={{ .Commit }} -X compose-generator/util.Date={{ .CommitDate }} -X compose-generator/util.BuiltBy=github-actions
dockers:
  - image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Version }}
      - ghcr.io/compose-generator/compose-generator:latest
      - chillibits/compose-generator:{{ .Version }}
      - chillibits/compose-generator:latest
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - predefined-services
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://www.compose-generator.com
      - --label=org.opencontainers.image.source=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache 2.0
      - --platform=linux/amd64
archives:
  - files:
      - LICENSE
      - predefined-services/*
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: publish
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    description: Easy to use cli to generate Docker Compose YAML configuration files.
    homepage: https://www.compose-generator.com
    license: Apache 2.0
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - ccom
      - lsb-release
    overrides:
      rpm:
        dependencies:
          - redhat-lsb
      apk:
        dependencies: []
    contents:
      - src: predefined-services/*
        dst: /usr/lib/compose-generator/predefined-services/
    empty_folders:
      - /usr/lib/compose-generator/templates
release:
  name_template: v{{.Tag}}
  prerelease: auto
  extra_files:
    - glob: ../predefined-services.tar.gz
announce:
  twitter:
    enabled: true
    message_template: 'Compose Generator {{.Tag}} is now available! Check out the new features: compose-generator.com!'