project_name: compose-generator
builds:
  - dir: src
    main: ./compose-generator.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 5
      - 6
      - 7
    ldflags:
      - -s -w -X compose-generator/util.Version={{ .Version }} -X compose-generator/util.Commit={{ .Commit }} -X compose-generator/util.Date={{ .CommitDate }} -X compose-generator/util.BuiltBy=github-actions
dockers:
  - image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-amd64
      - ghcr.io/compose-generator/compose-generator:latest-amd64
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-amd64
      - chillibits/compose-generator:{{ .Major }}-amd64
      - chillibits/compose-generator:latest-amd64
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: amd64
    extra_files:
      - predefined-services
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://www.compose-generator.com
      - --label=org.opencontainers.image.source=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache 2.0
      - --build-arg=ARCH=amd64
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-i386
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-i386
      - ghcr.io/compose-generator/compose-generator:latest-i386
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-i386
      - chillibits/compose-generator:{{ .Major }}-i386
      - chillibits/compose-generator:latest-i386
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: 386
    extra_files:
      - predefined-services
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://www.compose-generator.com
      - --label=org.opencontainers.image.source=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache 2.0
      - --build-arg=ARCH=386
      - --platform=linux/i386
  - image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v6
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v6
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-arm32v6
      - ghcr.io/compose-generator/compose-generator:latest-arm32v6
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v6
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v6
      - chillibits/compose-generator:{{ .Major }}-arm32v6
      - chillibits/compose-generator:latest-arm32v6
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: arm
    goarm: 6
    extra_files:
      - predefined-services
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://www.compose-generator.com
      - --label=org.opencontainers.image.source=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache 2.0
      - --build-arg=ARCH=armv6
      - --platform=linux/arm/v6
  - image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v7
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-arm32v7
      - ghcr.io/compose-generator/compose-generator:latest-arm32v7
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v7
      - chillibits/compose-generator:{{ .Major }}-arm32v7
      - chillibits/compose-generator:latest-arm32v7
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: arm
    goarm: 7
    extra_files:
      - predefined-services
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://www.compose-generator.com
      - --label=org.opencontainers.image.source=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache 2.0
      - --build-arg=ARCH=armv7
      - --platform=linux/arm/v7
docker_manifests:
  - name_template: chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v6
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
    skip_push: auto
  - name_template: chillibits/compose-generator:{{ .Major }}.{{ .Minor }}
    image_templates:
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-amd64
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-i386
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v6
      - chillibits/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v7
    skip_push: auto
  - name_template: chillibits/compose-generator:{{ .Major }}
    image_templates:
      - chillibits/compose-generator:{{ .Major }}-amd64
      - chillibits/compose-generator:{{ .Major }}-i386
      - chillibits/compose-generator:{{ .Major }}-arm32v6
      - chillibits/compose-generator:{{ .Major }}-arm32v7
    skip_push: auto
  - name_template: chillibits/compose-generator:latest
    image_templates:
      - chillibits/compose-generator:latest-amd64
      - chillibits/compose-generator:latest-i386
      - chillibits/compose-generator:latest-arm32v6
      - chillibits/compose-generator:latest-arm32v7
    skip_push: auto

  - name_template: ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v6
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
    skip_push: auto
  - name_template: ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-i386
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v6
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}.{{ .Minor }}-arm32v7
    skip_push: auto
  - name_template: ghcr.io/compose-generator/compose-generator:{{ .Major }}
    image_templates:
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-amd64
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-i386
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-arm32v6
      - ghcr.io/compose-generator/compose-generator:{{ .Major }}-arm32v7
    skip_push: auto
  - name_template: ghcr.io/compose-generator/compose-generator:latest
    image_templates:
      - ghcr.io/compose-generator/compose-generator:latest-amd64
      - ghcr.io/compose-generator/compose-generator:latest-i386
      - ghcr.io/compose-generator/compose-generator:latest-arm32v6
      - ghcr.io/compose-generator/compose-generator:latest-arm32v7
    skip_push: auto
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - predefined-services/*
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
nfpms:
  - id: publish
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    vendor: ChilliBits
    description: Easy to use cli to generate Docker Compose YAML configuration files.
    homepage: https://www.compose-generator.com
    license: Apache 2.0
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - ccom
      - lsb-release
    conflicts:
      - cgvg
    overrides:
      rpm:
        dependencies:
          - ccom
          - redhat-lsb
      apk:
        dependencies:
          - ccom
    contents:
      - src: predefined-services/*
        dst: /usr/lib/compose-generator/predefined-services/
      - src: /usr/bin/compose-generator
        dst: /usr/bin/cg
        type: symlink
      - src: bash_autocomplete.sh
        dst: /etc/bash_completion.d/compose-generator
      - dst: /usr/lib/compose-generator/templates
        type: dir
      - dst: /usr/lib/compose-generator/log
        type: dir
release:
  name_template: v{{ .Tag }}
  prerelease: auto
  extra_files:
    - glob: ./predefined-services/predefined-services.tar.gz
  footer: |
    ## What to do next?
    - [Install Compose Generator](https://www.compose-generator.com/install/linux/)
    - Visit [www.compose-generator.com](https://www.compose-generator.com) to test the new features
    - Follow [@composegen](https://twitter.com/composegen) on Twitter
changelog:
  use: github
  filters:
    exclude:
    - Merge pull request
    - Merge branch
milestones:
  - close: true
    fail_on_error: false