project_name: compose-generator
builds:
  - env: [CGO_ENABLED=0]
    dir: src
    main: ./compose-generator.go
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm64
dockers:
  - image_templates:
      - "ghcr.io/compose-generator/compose-generator:{{ .Version }}"
      - "ghcr.io/compose-generator/compose-generator:latest"
      - "docker.io/chillibits/compose-generator:{{ .Version }}"
      - "docker.io/chillibits/compose-generator:latest"
    dockerfile: Dockerfile
    use_buildx: true
    extra_files:
      - predefined-templates
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.source=https://github.com/compose-generator/compose-generator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2021-02-14T18:30:05Z01:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache 2.0
      - --platform=linux/amd64
archives:
  - files:
      - README.md
      - LICENSE
      - predefined-templates/*
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - maintainer: Marc Auberer <marc.auberer@chillibits.com>
    description: Easy to use cli to generate Docker Compose YAML configuration files.
    homepage: https://www.marc-auberer.com
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - curl
      - lsb-release
    overrides:
      rpm:
        dependencies:
          - redhat-lsb
          - curl
      apk:
        dependencies:
          - curl
    contents:
      - src: predefined-templates/*
        dst: /usr/lib/compose-generator/predefined-templates/
    empty_folders:
      - /usr/lib/compose-generator/templates
release:
  name_template: "v{{.Tag}}"
  github:
    owner: compose-generator
    name: compose-generator
  prerelease: auto