image: mariadb:${{MARIADB_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-mariadb
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
#? if services.frontend contains name == "nextcloud" | services.frontend contains name == "owncloud" | services.frontend contains name == "gitea" {
#  - frontend-database
#? }
#? if services.dbadmin contains name == "phpmyadmin" {
#  - mariadb-phpmyadmin
#? }
#? if services.dbadmin contains name == "adminer" {
#  - mariadb-adminer
#? }
ports:
  - ${{MARIADB_PORT}}:3306
volumes: 
  - ${{VOLUME_MARIADB_DATA}}:/var/lib/mysql
  - ${{VOLUME_MARIADB_LOGS}}:/var/log/mysql
env_file:
  - environment.env