image: mariadb:${{MARIADB_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-mariadb
restart: always
networks:
#! if has backend {
#!  - backend-database
#! }
#! if has service nextcloud {
#!  - frontend-database
#! }
#! if has service phpmyadmin {
#!  - mariadb-phpmyadmin
#! }
ports:
  - ${{MARIADB_PORT}}:3306
volumes: 
  - ${{VOLUME_MARIADB_DATA}}:/var/lib/mysql
  - ${{VOLUME_MARIADB_LOGS}}:/var/log/mysql
env_file:
  - environment.env