image: questdb/questdb:${{QUESTDB_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-questdb
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
ports:
  - ${{QUESTDB_API_PORT}}:9000
#? if var.QUESTDB_ENABLE_PG_WIRE_ENDPOINT == "yes" {
#  - 8812:8812
#? }

#? if var.QUESTDB_ENABLE_INFLUX_LINE_ENDPOINT == "yes" {
#  - 9009:9009
#? }

#? if var.QUESTDB_ENABLE_HEALTH_ENDPOINT == "yes" {
#  - 9003:9003
#? }
volumes: 
  - ${{VOLUME_QUESTDB_DATA}}:/root/.questdb/db
  - ${{VOLUME_QUESTDB_CONFIG}}:/root/.questdb/conf