image: questdb/questdb:${{QUESTDB_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-questdb
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
ports:
  - ${{QUESTDB_API_PORT}}:9000
  - ${{QUESTDB_PG_WIRE_PORT}}:8812
  - ${{QUESTDB_INFLUX_LINE_PORT}}:9009
#? if vars.QUESTDB_ENABLE_HEALTH_ENDPOINT == "yes" {
#  - 9003:9003
#? }
volumes: 
  - ${{VOLUME_QUESTDB_DATA}}:/root/.questdb/db
  - ${{VOLUME_QUESTDB_CONFIG}}:/root/.questdb/conf
env_file:
  - environment.env