build: ${{SPRING_MAVEN_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-spring-maven
restart: always
networks:
#? if has services.frontend {
#  - frontend-backend
#? }
#? if has services.database {
#  - backend-database
#? }
ports:
  - ${{SPRING_MAVEN_PORT}}:8080
env_file:
  - environment.env