build: backend
container_name: ${{PROJECT_NAME_CONTAINER}}-backend
restart: always
networks:
#! if has frontend {
#!  - frontend-backend
#! }
#! if has database {
#!  - backend-database
#! }
ports:
  - ${{HOST_BACKEND_PORT}}:8080
env_file:
  - environment.env
depends_on:
#! if has database {
#!  - database
#! }