image: ghcr.io/livepoll/live-poll-dev:${{LIVE_POLL_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-live-poll-api
restart: always
ports:
  - ${{LIVE_POLL_PORT}}:80
env_file:
  - environment.env