image: elasticsearch:${{ELASTICSEARCH_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-elasticsearch
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
#? if services.dbadmin contains name == "elasticsearch-hq" {
#  - elasticsearch-elasticsearchhq
#? }
#? if services.dbadmin contains name == "adminer" {
#  - elasticsearch-adminer
#? }
ports:
  - ${{ELASTICSEARCH_PORT}}:9200
volumes: 
  - ${{VOLUME_ELASTICSEARCH_DATA}}:/usr/share/elasticsearch/data
environment:
  #- transport.host=0.0.0.0
  - discovery.type=single-node