project_name: Test
compose_version: 3.8
production_ready: true
services:
  - name: angular
    type: frontend
    params:
      ANGULAR_PORT: 81
  - name: spring-maven
    type: backend
    params:
      SPRING_MAVEN_PORT: 8081
      SPRING_MAVEN_VERSION: 2.4.3.RELEASE
      SPRING_MAVEN_LANGUAGE: groovy
      SPRING_MAVEN_PACKAGE_NAME: com.chillibits.test