build: ${{FASTAPI_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-fastapi
restart: always
networks:
#? if has services.frontend {
#  - frontend-backend
#? }
#? if has services.database {
#  - backend-database
#? }
ports:
  - ${{FASTAPI_PORT}}:80