image: elastichq/elasticsearch-hq:${{ELASTICSEARCH_HQ_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-dbadmin-elasticsearch-hq
networks:
#? if services.database contains name == "elasticsearch" {
#   - elasticsearch-elasticsearchhq
#? }
ports:
  - ${{ELASTICSEARCH_HQ_PORT}}:5000
