providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: ${{TRAEFIK_DEFAULT_EMAIL}}
      storage: acme.json
      tlsChallenge: {}

global:
  checkNewVersion: true