providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  cert-resolver:
    acme:
      email: your-email@chillibits.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web