build: ${{GIN_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-gin
restart: always
networks:
#? if has services.frontend {
#  - frontend-backend
#? }
#? if has services.database {
#  - backend-database
#? }
ports:
  - ${{GIN_PORT}}:8080