image: mysql:${{MYSQL_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-mysql
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
#? if services.frontend contains name == "nextcloud" | services.frontend contains name == "owncloud" | services.frontend contains name == "gitea" | services.frontend contains name == "jira" {
#  - frontend-database
#? }
#? if services.dbadmin contains name == "phpmyadmin" {
#  - mariadb-phpmyadmin
#? }
#? if services.dbadmin contains name == "adminer" {
#  - mariadb-adminer
#? }
ports:
  - ${{MYSQL_PORT}}:3306
volumes: 
  - ${{VOLUME_MYSQL_DATA}}:/var/lib/mysql
  - ${{VOLUME_MYSQL_LOGS}}:/var/log/mysql
env_file:
  - environment.env