<html>
    <head>
        <title>Example page</title>
    </head>
    <body>
        <h1>
            Current date and time: 
            <?php echo(date('m/d/Y h:i:s a', time())) ?>
        </h1>
        <b>This page was generated by <a href="https://compose-generator.com" target="_blank">Compose Generator</a></b>
    </body>
</html>