build: ${{SPRING_GRADLE_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-spring-gradle
restart: always
networks:
#! if has frontend {
#!  - frontend-backend
#! }
#! if has database {
#!  - backend-database
#! }
ports:
  - ${{SPRING_GRADLE_PORT}}:8080
env_file:
  - environment.env