image: itzg/minecraft-server
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-minecraft
restart: always
volumes:
  - ${{VOLUME_MINECRAFT_DATA}}:/data
ports:
  - ${{MINECRAFT_PORT}}:25565
environment:
  - EULA=${{MINECRAFT_EULA}}
  - VERSION=${{MINECRAFT_VERSION}}
  - MEMORY=${{MINECRAFT_MEM}}G