build: ${{DJANGO_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-django
restart: always
networks:
#! if has frontend {
#!  - frontend-backend
#! }
#! if has database {
#!  - backend-database
#! }
ports:
  - ${{DJANGO_PORT}}:8000