image: osixia/phpldapadmin:${{PHPLDAPADMIN_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-db-admin-phpldapadmin
networks:
  - openldap-phpldapadmin
ports:
  - 443:443
  - 80:80
environment:
  PHPLDAPADMIN_LDAP_HOSTS: ยง{{OPENLDAP_HOST}}
  PHPLDAPADMIN_HTTPS: false