build: ${{FLASK_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend
restart: always
networks:
#! if has frontend {
#!  - frontend-backend
#! }
#! if has database {
#!  - backend-database
#! }
ports:
  - ${{FLASK_PORT}}:5000
env_file:
  - environment.env
depends_on:
#! if has database {
#!  - database
#! }