# Docker compose file for ${{PROJECT_NAME}}
version: '3.9'

services:
  # ${{PROJECT_NAME}} React frontend
  frontend:
    build: frontend
    container_name: ${{PROJECT_NAME_CONTAINER}}-frontend
    restart: always
    networks:
      - react-spring
    ports:
      - ${{HOST_FRONTEND_PORT}}:80
    depends_on:
      - backend

  # ${{PROJECT_NAME}} Spring backend
  backend:
    build: backend
    container_name: ${{PROJECT_NAME_CONTAINER}}-backend
    restart: always
    networks:
      - react-spring
      - spring-mysql
    ports:
      - ${{HOST_BACKEND_PORT}}:8080
    env_file:
      - environment.env
    depends_on:
      - database

  # MySQL database
  database:
    image: mysql:${{MYSQL_VERSION}}
    container_name: ${{PROJECT_NAME_CONTAINER}}-db
    restart: always
    volumes:
      - ${{VOLUME_MYSQL_DATA}}:/var/lib/mysql
      - ${{VOLUME_MYSQL_LOGS}}:/var/log/mysql
    networks:
      - spring-mysql
      - mysql-phpmyadmin
    env_file:
      - environment.env

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${{PMA_VERSION}}
    container_name: ${{PROJECT_NAME_CONTAINER}}-phpmyadmin
    networks:
      - mysql-phpmyadmin
    ports:
      - ${{HOST_PMA_PORT}}:80
    volumes:
      - /sessions
    env_file:
      - environment.env
    depends_on:
      - database

networks:
  react-spring: {}
  spring-mysql: {}
  mysql-phpmyadmin: {}