image: redis:${{REDIS_VERSION}}-alpine
container_name: ${{PROJECT_NAME_CONTAINER}}-db-redis
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
ports:
  - ${{REDIS_PORT}}:5432
volumes: 
  - ${{VOLUME_REDIS_DATA}}:/data
env_file:
  - environment.env
command: redis-server --requirepass "$REDIS_PASSWORD"