image: adminer:${{ADMINER_VERSION}}
container_name: ${{PROJECT_NAME_CONTAINER}}-dbadmin-adminer
networks:
#? if services.database contains name == "postgres" {
#   - postgres-adminer
#? }
#? if services.database contains name == "mysql" {
#   - mysql-adminer
#? }
#? if services.database contains name == "mariadb" {
#   - mariadb-adminer
#? }
ports:
  - ${{ADMINER_PORT}}:8080
env_file:
  - environment.env
depends_on:
  - database
