image: postgres:${{POSTGRES_VERSION}}-alpine
container_name: ${{PROJECT_NAME_CONTAINER}}-db-postgres
restart: always
networks:
#? if has services.backend {
#  - backend-database
#? }
#? if services.frontend contains name == "nextcloud" | services.frontend contains name == "owncloud" | services.frontend contains name == "gitea" | services.frontend contains name == "sonarqube" | services.frontend contains name == "jira" | services.frontend contains name == "bitbucket" | services.frontend contains name == "accent" {
#  - frontend-database
#? }
#? if services.dbadmin contains name == "pgadmin" {
#  - postgres-pgadmin
#? }
#? if services.dbadmin contains name == "adminer" {
#  - postgres-adminer
#? }
#? if services.frontend contains name == "paperless-ng" {
#  - paperless-ng-postgres
#? }
ports:
  - ${{POSTGRES_PORT}}:5432
volumes: 
  - ${{VOLUME_POSTGRES_DATA}}:/var/lib/postgresql/data
  - ${{VOLUME_POSTGRES_INIT}}:/docker-entrypoint-initdb.d/
env_file:
  - environment.env