site_name: Compose Generator
site_url: https://www.compose-generator.com
site_description: Setup your application in a matter of seconds
site_author: Marc Auberer
copyright: Made with ❤️ by Compose Generator contributors.
repo_name: compose-generator/compose-generator
repo_url: https://github.com/compose-generator/compose-generator
edit_uri: edit/dev/docs/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: static/avatar.png
  favicon: static/favicon-48x48.ico
  include_search_page: false
  search_index_only: true
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default # Light mode
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: slate # Dark mode
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search:
      prebuild_index: python
      lang:
      - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/compose-generator/compose-generator
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/composegen
    - icon: fontawesome/brands/medium
      link: https://medium.com/p/d4356d38922d
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/chillibits/compose-generator

nav:
  - Home: index.md
  - intro.md
  - Install:
    - install/docker.md
    - install/linux.md
    - install/windows.md
    - install/npm.md
  - quick-start.md
  - Usage:
    - usage/generate.md
    - usage/add.md
    - usage/remove.md
    - usage/template.md
    - usage/install.md
  - contributing.md

markdown_extensions:
  - codehilite
  - meta
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences