site_name: Compose Generator
site_description: Deliver Go binaries as fast and easily as possible
site_author: Marc Auberer
copyright: Made with ❤️ by Compose Generator contributors.
repo_name: compose-generator/compose-generator
repo_url: https://github.com/compose-generator/compose-generator
edit_uri: edit/main/docs/docs/

theme:
  name: material
  language: en
  logo: static/avatar.png
  favicon: static/favicon-48x48.ico
  include_search_page: false
  search_index_only: true
  features:
    - navigation.instant
  palette:
    - scheme: default # Light mode
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: slate # Dark mode
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      prebuild_index: python
      lang:
      - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/compose-generator/compose-generator
    - icon: fontawesome/brands/medium
      link: https://medium.com/p/d4356d38922d
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/chillibits/compose-generator

nav:
- Home: index.md
- Introduction: intro.md
- Install:
  - install/docker.md
  - install/linux.md
  - install/windows.md
- quick-start.md
- Usage:
  - usage/generate.md
  - usage/add.md
  - usage/remove.md
  - usage/template.md
  - usage/install.md
- contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences