build: ${{NODE_SOURCE_DIRECTORY}}
container_name: ${{PROJECT_NAME_CONTAINER}}-backend-node
restart: always
networks:
#! if has frontend {
#!  - frontend-backend
#! }
#! if has database {
#!  - backend-database
#! }
ports:
  - ${{NODE_PORT}}:80