# Go Build

name: Go Build

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    branches: [ main, dev, feature/* ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Prepare environment
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run vet & lint
      run: |
        cd src
        go vet ./...
        golint ./...
    - name: Run build
      run: |
        cd src
        go build -x
