# Predefined service validation
name: Service validation

on:
  push:
    paths:
      - predefined-services/**
  pull_request:
    branches:
      - main
      - release/**
      - feature/**

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Prepare environment.env
      working-directory: .github/scripts/service-validator
      run: pip install -r requirements.txt
      
    - name: Run validation script
      working-directory: .github/scripts/service-validator
      run: python predefined-service-validator.py