# Predefined service testing
name: Service testing

on:
  pull_request:
    paths:
      - predefined-services/**
    branches:
      - main
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upgrade apt packages
      run: sudo apt-get update && sudo apt-get upgrade -y

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Prepare environment.env
      working-directory: .github/scripts/service-tester
      run: pip install -r requirements.txt

    - name: Install CCom
      run: |
        curl -fsSL https://server.chillibits.com/files/repo/gpg | sudo apt-key add -
        sudo add-apt-repository "deb https://repo.chillibits.com/ubuntu-$(lsb_release -cs) $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install ccom

    - name: Install CG
      run: ./install.sh
      
    - name: Run testing script
      working-directory: .github/scripts/service-tester
      run: python predefined-service-tester.py
      env:
        COMPOSE_GENERATOR_CI: 1