# Predefined service testing
name: Service testing

on:
  pull_request:
    paths:
      - predefined-services/**
    branches:
      - main
      - release/**
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Prepare environment.env
      working-directory: .github/scripts/service-tester
      run: pip install -r requirements.txt

    - name: Install CG
      run: ./install.sh
      
    - name: Run testing script
      working-directory: .github/scripts/service-tester
      run: python predefined-service-tester.py