# Go Tests

name: Go Tests

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    branches: [ main, dev, test/*, tests/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install CCom
      run: |
        curl -fsSL https://server.chillibits.com/files/repo/gpg | sudo apt-key add -
        sudo add-apt-repository "deb https://admin.repo.chillibits.com/repository/ubuntu-$(lsb_release -cs) $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install ccom

    - name: Run tests
      working-directory: src
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Install GoSec
      run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.8.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.8.1

    - name: Run security scan
      working-directory: src
      run: gosec ./...