# Publish to WinGet
name: Publish to WinGet

on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: ChilliBits.ComposeGenerator
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
